version: "3.7"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network: