version: "3.7"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg://roasis:roasispassword@postgres:5432/roasis_db
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - my_network

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    depends_on:
      - backend
    networks:
      - my_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=roasis_db
      - POSTGRES_USER=roasis
      - POSTGRES_PASSWORD=roasispassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    ports:
      - "5432:5432"

networks:
  my_network:

volumes:
  postgres_data:
